# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af7a8b8427660367a5e6d922cdd4108aea6564d90ec46ea041dbca5e28a0e5d0a102209200587e3a2aab7137f5932ca0276d388765e062b6752053a0ba064ad

test:
  secret_key_base: 27f5ff8487225fc0e2f826e9b633e3a5f79b82fbf99b879859ab9140a17ac6e9c85c3e3c03b721c9fd94f5f53157531104bc1acf3a90b2db51d1b350cc7d2bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
